import { useMediaSource } from '../../../lib/hooks/use-media-source'
import { memo, useCallback, useMemo, useRef, useState } from 'react'
import { VideoItem as VideoItemDto } from 'tapestry-core/src/data-format/schemas/item'
import {
  MediaPlayer,
  getVideoElement,
  useMediaEvent,
  VideoJSOptions,
  MediaPlayerProps,
} from '../../../lib/media-player'
import { captureVideoFrame } from '../../../../lib/dom'
import { useMediaParams } from '../../hooks/use-media-params'
import { useAutoplay } from '../../hooks/use-autoplay'
import Player from 'video.js/dist/types/player'
import { Id } from 'tapestry-core/src/data-format/schemas/common'
import { useTapestryConfig } from '../..'
import { VideoPlayOverlay } from '../../video-play-overlay'
import styles from './styles.module.css'
import { getPrimaryThumbnail } from '../../../../view-model/utils'
import { setItemIsPlaying } from '../../../../view-model/store-commands/tapestry'

function useVideoThumbnail(dto: VideoItemDto, player: Player | undefined) {
  const [thumbnail, setThumbnail] = useState(getPrimaryThumbnail(dto))
  const frameThumbnailRef = useRef<string>(undefined)

  async function setVideoFrameAsThumb() {
    const video = getVideoElement(player)
    const hasCustomThumbnail = dto.thumbnail?.renditions.find(
      (r) => r.isPrimary && !r.isAutoGenerated,
    )

    if (!video || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA || hasCustomThumbnail) {
      return
    }

    if (thumbnail && thumbnail === frameThumbnailRef.current) {
      URL.revokeObjectURL(thumbnail)
    }
    const blob = await captureVideoFrame(video)
    const url = URL.createObjectURL(blob)
    frameThumbnailRef.current = url
    setThumbnail(url)
  }

  useMediaEvent(player, 'pause', (p) => {
    if (!p.seeking()) {
      void setVideoFrameAsThumb()
    }
  })
  useMediaEvent(player, 'seeked', (p) => {
    if (p.paused()) {
      void setVideoFrameAsThumb()
    }
  })

  return thumbnail
}

export interface VideoItemPlayerProps extends Partial<MediaPlayerProps<'video'>> {
  id: Id
  mediaType?: string
}

export const VideoItemPlayer = memo(
  ({ id, mediaType, style, onPlayerReady, ...playerProps }: VideoItemPlayerProps) => {
    const { useStoreData, useDispatch } = useTapestryConfig()
    const dispatch = useDispatch()
    const onStart = useCallback(() => dispatch(setItemIsPlaying(id, true)), [dispatch, id])
    const onStop = useCallback(() => dispatch(setItemIsPlaying(id, false)), [dispatch, id])
    const dto = useStoreData(`items.${id}.dto`) as VideoItemDto
    const isInteractive = useStoreData('interactiveElement')?.modelId === id
    const src = useMediaSource(dto.source)
    const [player, setPlayer] = useState<Player>()
    const mediaParams = useMediaParams(id)

    useAutoplay(id, player, mediaParams.autoplay)

    useMediaEvent(player, 'play', onStart)
    useMediaEvent(player, 'pause', onStop)
    useMediaEvent(player, 'ended', onStop)

    const showVideo = player?.paused() === false || isInteractive

    const thumbnail = useVideoThumbnail(dto, player)

    const options = useMemo<VideoJSOptions>(
      () => ({
        src,
        mediaType,
        controls: true,
        crossorigin: 'anonymous',
        preload: 'metadata',
      }),
      [src, mediaType],
    )

    return (
      <div className={styles.root}>
        <MediaPlayer
          component="video"
          options={options}
          onPlayerReady={(player) => {
            setPlayer(player)
            onPlayerReady?.(player)
          }}
          startTime={mediaParams.startTime ?? dto.startTime ?? 0}
          stopTime={mediaParams.stopTime ?? dto.stopTime ?? undefined}
          // The video is hidden in order to optimize the Safari layering algorithm
          style={{
            display: showVideo ? 'block' : 'none',
            width: '100%',
            height: '100%',
            ...style,
          }}
          {...playerProps}
        />
        {thumbnail && (
          <img
            src={thumbnail}
            // Images that may be loaded via `fetch` elsewhere must always be loaded with CORS policy "anonymous"
            // in order to prevent cached CORS header errors in Chrome.
            crossOrigin="anonymous"
            style={{
              display: showVideo ? 'none' : 'block',
              height: '100%',
              width: '100%',
              objectFit: 'cover',
            }}
          />
        )}
        {!isInteractive && player?.paused() && (
          <VideoPlayOverlay itemSize={dto.size} type="play_arrow" />
        )}
      </div>
    )
  },
)
