import { ItemDto } from 'tapestry-shared/src/data-transfer/resources/dtos/item'
import { Button, MenuItemButton } from 'tapestry-core-client/src/components/lib/buttons/index'
import { SimpleModal } from 'tapestry-core-client/src/components/lib/modal/index'
import styles from './styles.module.css'
import { Icon } from 'tapestry-core-client/src/components/lib/icon/index'
import { Text } from 'tapestry-core-client/src/components/lib/text/index'
import { FilePicker } from 'tapestry-core-client/src/components/lib/file-picker/index'
import { CSSProperties, useState } from 'react'
import { DropArea } from 'tapestry-core-client/src/components/lib/drop-area'
import { dataTransferToFiles } from '../../../../stage/data-transfer-handler'
import { useMediaSource } from 'tapestry-core-client/src/components/lib/hooks/use-media-source'
import clsx from 'clsx'
import { useAsyncAction } from 'tapestry-core-client/src/components/lib/hooks/use-async-action'
import { resource } from '../../../../services/rest-resources'
import { itemSizes, uploadAsset } from '../../../../model/data/utils'
import { LoadingSpinner } from 'tapestry-core-client/src/components/lib/loading-spinner/index'
import { compressImage, getImageItemSize, getImageSize } from '../../../../lib/media'
import { Size } from 'tapestry-core/src/data-format/schemas/common'
import { aspectRatio } from 'tapestry-core/src/lib/geometry'
import { useTapestryDataSyncCommands } from '../../../../pages/tapestry/tapestry-providers'

interface NoCustomThumbnailOptionProps {
  item: ItemDto
}

function NoCustomThumbnailOption({ item }: NoCustomThumbnailOptionProps) {
  if (item.type === 'audio') {
    return (
      <>
        <Icon icon="hide_image" />
        <Text variant="bodyXs">No thumbnail</Text>
      </>
    )
  }

  return (
    <>
      <Icon icon="wand_stars" />
      <Text variant="bodyXs">Auto-generated</Text>
    </>
  )
}

interface ChangeThumbnailButtonProps {
  onClick: () => unknown
  className?: string
}

export function ChangeThumbnailButton({ onClick, className }: ChangeThumbnailButtonProps) {
  return (
    <MenuItemButton shortcut="meta + alt + T" onClick={onClick} className={className}>
      Change thumbnail
    </MenuItemButton>
  )
}

interface ItemThumbnailProps {
  thumbnail?: string | null
  className?: string
  customBlobUrl: string | null
  style?: CSSProperties
}

function ItemThumbnail({ thumbnail, className, customBlobUrl, style }: ItemThumbnailProps) {
  const src = customBlobUrl ?? thumbnail

  return src ? <img src={src} className={className} style={style} alt="Thumbnail preview" /> : null
}

async function getNewItemSize(item: ItemDto, thumbnail?: File) {
  if (item.type === 'audio') {
    return thumbnail
      ? getImageItemSize(thumbnail, item.size.width)
      : {
          width: item.size.width,
          height: itemSizes.audio.height,
        }
  }
}

interface ChangeThumbnailDialogProps {
  onClose: () => unknown
  item: ItemDto
}

export function ChangeThumbnailDialog({ onClose, item }: ChangeThumbnailDialogProps) {
  const [useAutoGenerated, setUseAutoGenerated] = useState(false)
  const [selectedFile, setSelectedFile] = useState<{ file: File; size: Size }>()
  const [customThumbnailItemSize, setCustomThumbnailItemSize] = useState<Size>()
  const customThumbnail = item.thumbnail?.renditions.find((r) => !r.isAutoGenerated)
  const autoThumbnail = item.thumbnail?.renditions.find((r) => r.isPrimary && r.isAutoGenerated)
  const primaryThumbnail = customThumbnail ?? autoThumbnail
  const blobUrl = useMediaSource(selectedFile?.file ?? customThumbnail?.source ?? null)
  const { reload } = useTapestryDataSyncCommands()

  const onNewFile = async (file: File) => {
    const newItemSize = await getNewItemSize(item, file)
    setCustomThumbnailItemSize(newItemSize)
    const compressed = await compressImage(file, newItemSize)
    const size = await getImageSize(compressed)
    setUseAutoGenerated(false)
    setSelectedFile({ file: compressed, size })
  }

  const { trigger: save, loading } = useAsyncAction(async ({ signal }) => {
    const newSize = useAutoGenerated ? await getNewItemSize(item) : customThumbnailItemSize
    if (useAutoGenerated) {
      if (customThumbnail) {
        await resource('items').update(
          { id: item.id },
          {
            type: item.type,
            thumbnail: null,
            ...(newSize ? { size: newSize } : {}),
          },
          undefined,
          { signal },
        )
      }
    } else if (selectedFile) {
      const key = await uploadAsset(
        selectedFile.file,
        {
          tapestryId: item.tapestryId,
          type: 'tapestry-asset',
        },
        { signal },
      )
      await resource('items').update(
        { id: item.id },
        {
          type: item.type,
          thumbnail: {
            source: key,
            size: selectedFile.size,
          },
          ...(newSize ? { size: newSize } : {}),
        },
        undefined,
        { signal },
      )
    }
    reload({ items: [item.id] })
    onClose()
  })

  return (
    <SimpleModal
      title="Thumbnail Preview"
      cancel={{ onClick: onClose }}
      confirm={{ text: 'Confirm', onClick: save }}
    >
      <div className={styles.root}>
        <div className={styles.previewContainer}>
          <ItemThumbnail
            thumbnail={primaryThumbnail?.source}
            customBlobUrl={blobUrl}
            className={styles.previewImage}
            style={{ aspectRatio: aspectRatio(customThumbnailItemSize ?? item.size) }}
          />
          {loading && (
            <div className={styles.loadingIndicatorWrapper}>
              <LoadingSpinner size="80px" />
            </div>
          )}
        </div>
        <div className={styles.thumbnailSelector}>
          <Text variant="body" style={{ fontWeight: 600 }}>
            Choose thumbnail
          </Text>
          <Button
            aria-label="Don't use custom thumbnail"
            className={clsx(styles.autoGenerated, styles.thumbnailContainer, {
              [styles.active]: useAutoGenerated,
            })}
            variant="clear"
            onClick={() => setUseAutoGenerated(true)}
          >
            {autoThumbnail ? <img className={styles.fitImage} src={autoThumbnail.source} /> : null}
            <div className={styles.overlayContainer}>
              <NoCustomThumbnailOption item={item} />
            </div>
          </Button>
          <FilePicker accept="image/*" onChange={onNewFile}>
            <DropArea
              allowDrop={(items) => items.some((i) => i.type.startsWith('image'))}
              onDrop={async (e) => {
                const image = (await dataTransferToFiles(e.dataTransfer)).find((f) =>
                  f.type.startsWith('image'),
                )
                if (image) {
                  await onNewFile(image)
                }
              }}
              {...(useAutoGenerated
                ? {
                    onClick: (e) => {
                      e.preventDefault()
                      setUseAutoGenerated(false)
                    },
                  }
                : {})}
              classes={{
                root: clsx(styles.dropArea, styles.thumbnailContainer),
                dropHint: clsx(styles.dropHint, { [styles.hasSelected]: !!blobUrl }),
              }}
              alwaysVisible
              subtitle="Upload custom thumbnail"
            >
              {blobUrl && (
                <>
                  <img src={blobUrl} className={styles.fitImage} />
                  {!useAutoGenerated && (
                    <div className={styles.selectedImageOverlay}>
                      <Icon icon="image" style={{ fontSize: '28px' }} />
                      <Text variant="bodySm" style={{ fontWeight: 600 }}>
                        Change Image
                      </Text>
                    </div>
                  )}
                </>
              )}
            </DropArea>
          </FilePicker>
        </div>
      </div>
    </SimpleModal>
  )
}
