-- CreateTable
CREATE TABLE "ImageAsset" (
  "id" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ImageAsset_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ImageAssetRendition" (
  "id" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  "assetId" TEXT NOT NULL,
  "isPrimary" BOOLEAN NOT NULL,
  "isAutoGenerated" BOOLEAN NOT NULL,
  "source" TEXT NOT NULL,
  "format" TEXT NOT NULL,
  "width" INTEGER NOT NULL,
  "height" INTEGER NOT NULL,
  CONSTRAINT "ImageAssetRendition_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE
  "ImageAssetRendition"
ADD
  CONSTRAINT "ImageAssetRendition_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "ImageAsset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE
  "Item"
ADD
  COLUMN "thumbnailId" TEXT;

-- AddForeignKey
ALTER TABLE
  "Item"
ADD
  CONSTRAINT "Item_thumbnailId_fkey" FOREIGN KEY ("thumbnailId") REFERENCES "ImageAsset"("id") ON DELETE
SET
  NULL ON UPDATE CASCADE;

WITH "items" AS (
  SELECT
    "i"."id" AS "itemId",
    COALESCE("i"."customThumbnail", "i"."thumbnail") AS "thumbnail",
    ("i"."customThumbnail" IS NULL) AS "isAutoGenerated",
    "i"."thumbnailWidth",
    "i"."thumbnailHeight"
  FROM
    "Item" "i"
  WHERE
    "i"."customThumbnail" IS NOT NULL
    OR "i"."thumbnail" IS NOT NULL
),
"assets" AS (
  INSERT INTO
    "ImageAsset" ("id", "updatedAt")
  SELECT
    gen_random_uuid(),
    now()
  FROM
    "items" RETURNING "id"
),
"paired" AS (
  SELECT
    "i"."itemId",
    "i"."thumbnail",
    "i"."isAutoGenerated",
    "i"."thumbnailWidth",
    "i"."thumbnailHeight",
    "a"."id" AS "assetId"
  FROM
    (
      SELECT
        "itemId",
        "thumbnail",
        "isAutoGenerated",
        "thumbnailWidth",
        "thumbnailHeight",
        row_number() OVER (
          ORDER BY
            "itemId"
        ) AS "rn"
      FROM
        "items"
    ) "i"
    JOIN (
      SELECT
        "id",
        row_number() OVER (
          ORDER BY
            "id"
        ) AS "rn"
      FROM
        "assets"
    ) "a" USING ("rn")
),
"renditions" AS (
  INSERT INTO
    "ImageAssetRendition" (
      "id",
      "updatedAt",
      "assetId",
      "source",
      "isPrimary",
      "isAutoGenerated",
      "format",
      "width",
      "height"
    )
  SELECT
    gen_random_uuid(),
    now(),
    "p"."assetId",
    "p"."thumbnail",
    TRUE,
    "p"."isAutoGenerated",
    LOWER(
      SUBSTRING(
        "p"."thumbnail"
        FROM
          '\.(\w+)(\?|$)'
      )
    ),
    COALESCE("p"."thumbnailWidth", 0),
    COALESCE("p"."thumbnailHeight", 0)
  FROM
    "paired" "p" RETURNING "id",
    "assetId"
)
UPDATE
  "Item" "i"
SET
  "thumbnailId" = "p"."assetId"
FROM
  "paired" "p"
WHERE
  "i"."id" = "p"."itemId";

-- AlterTable
ALTER TABLE
  "Item" DROP COLUMN "customThumbnail",
  DROP COLUMN "thumbnail",
  DROP COLUMN "thumbnailHeight",
  DROP COLUMN "thumbnailWidth";
