import { PublicUserProfileDto, UserDto } from './data-transfer/resources/dtos/user'
import { Size } from 'tapestry-core/src/data-format/schemas/common'

export function userToPublicProfileDto(user: UserDto): PublicUserProfileDto {
  return {
    id: user.id,
    createdAt: user.createdAt,
    updatedAt: user.updatedAt,
    givenName: user.givenName,
    familyName: user.familyName,
    username: user.username,
    avatar: user.avatar,
  }
}

export function generateItemThumbnailRenditionName(
  itemId: string,
  opts: { isPrimary: boolean; isAutoGenerated: boolean; format: string; size: Size },
) {
  const autoPrefix = opts.isAutoGenerated ? 'auto' : 'custom'
  const primaryPrefix = opts.isPrimary ? 'primary' : 'derived'
  return `${itemId}-${autoPrefix}-${primaryPrefix}-thumbnail-${opts.format}-${opts.size.width}x${opts.size.height}`
}
