import { s3Service, tapestryKey } from '../services/s3-service.js'
import { ensureTransaction, prisma } from '../db.js'
import { ImageAssetRendition, Item, Prisma } from '@prisma/client'
import { scheduleTapestryThumbnailGeneration } from '../resources/tapestries.js'
import { ThumbnailRenditionOutput } from './thumbnail-generators/index.js'
import { generateItemThumbnailRenditionName } from 'tapestry-shared/src/utils.js'
import { parseDBItemSource } from '../transformers/item.js'
import { downloadImageToArrayBuffer } from './utils.js'
import { generateThumbnail } from './thumbnail-generators/image.js'
import sharp from 'sharp'

async function storeThumbnailRendition(
  item: Item,
  isPrimary: boolean,
  generate: (item: Item) => Promise<ThumbnailRenditionOutput | null | undefined>,
  tx?: Prisma.TransactionClient,
) {
  try {
    console.log(`Generating thumbnail rendition for item ${item.id}...`)
    const output = await generate(item)
    if (!output) {
      console.log(`[${item.id}] Thumbnail generation failed.`)
      return
    }

    console.log(`[${item.id}] Thumbnail generated. Uploading to S3...`)

    const { data, extension, format, size } = output
    const renditionName = generateItemThumbnailRenditionName(item.id, {
      format,
      size,
      isPrimary,
      isAutoGenerated: true,
    })
    const renditionKey = tapestryKey(item.tapestryId, `${renditionName}.${extension}`)

    await s3Service.putObject(renditionKey, data, `image/${format}`)

    console.log(`[${item.id}] Thumbnail uploaded. Updating db records...`)
    await ensureTransaction(tx, async (tx) => {
      const assetId =
        item.thumbnailId ??
        (
          await tx.imageAsset.create({
            data: { thumbnailForItems: { connect: { id: item.id } } },
          })
        ).id

      await tx.imageAssetRendition.create({
        data: {
          source: renditionKey,
          format,
          isPrimary,
          isAutoGenerated: true,
          width: size.width,
          height: size.height,
          assetId,
        },
      })
    })

    if (isPrimary) {
      await scheduleTapestryThumbnailGeneration(item.tapestryId)
    }

    console.log(`[${item.id}] Done.`)
    return output
  } catch (error) {
    console.error('Error while generating item thumbnail', error)
  }
}

const LEVELS_OF_DETAIL = [256, 512, 1024, 2048, 4096]

function hasRenditionAtLOD(renditions: ImageAssetRendition[], lod: number) {
  return renditions.some(
    ({ width, height }) =>
      width < 1.5 * lod && height < 1.5 * lod && (width > 0.75 * lod || height > 0.75 * lod),
  )
}

export async function processItemThumbnail(
  itemId: string,
  generatePrimaryThumbnail: () => Promise<ThumbnailRenditionOutput | undefined>,
) {
  const loadItem = () =>
    prisma.item.findUniqueOrThrow({
      where: { id: itemId },
      include: { thumbnail: { include: { renditions: true } } },
    })

  let item = await loadItem()
  if (!item.scheduledThumbnailProcessing) return

  const forceRegenerate = item.scheduledThumbnailProcessing === 'recreate'

  // Never regenerate thumbnails if they have not been automatically generated in the first place.
  // In particular, if the user has manually uploaded a custom thumbnail, we should never delete it
  // and replace it with an automatically generated one.
  if (forceRegenerate && item.thumbnail?.renditions.every((r) => r.isAutoGenerated)) {
    await prisma.imageAsset.delete({ where: { id: item.thumbnail.id } })
    item = await loadItem()
  }

  let primaryRendition = item.thumbnail?.renditions.find((r) => r.isPrimary)
  let primaryRenditionBitmap: Buffer<ArrayBufferLike>

  if (primaryRendition) {
    primaryRenditionBitmap = await downloadImageToArrayBuffer(
      (await parseDBItemSource(primaryRendition.source)).source,
    )
    if (primaryRendition.width === 0 || primaryRendition.height === 0) {
      // In some cases we have invalid dimensions stored in the database. Infer the correct ones from the bitmap.
      const meta = await sharp(primaryRenditionBitmap, { failOn: 'none' }).metadata()
      primaryRendition = await prisma.imageAssetRendition.update({
        where: { id: primaryRendition.id },
        data: {
          width: meta.width,
          height: meta.height,
        },
      })
    }
  } else {
    const output = await storeThumbnailRendition(item, true, generatePrimaryThumbnail)

    if (!output) {
      console.error(`Failed to generate thumbnail for item ${itemId}.`)
      return
    }

    // Reload the item so that all foreign keys and relations are loaded properly after any updates that may
    // have been done in storeThumbnailRendition above.
    item = await loadItem()
    primaryRendition = item.thumbnail!.renditions.find((r) => r.isPrimary)!
    primaryRenditionBitmap = output.data
  }

  const derivedRenditions = item.thumbnail?.renditions.filter((r) => !r.isPrimary) ?? []
  const maxPrimaryDim = Math.max(primaryRendition.width, primaryRendition.height)

  for (const lod of LEVELS_OF_DETAIL) {
    if (maxPrimaryDim > lod && !hasRenditionAtLOD([primaryRendition, ...derivedRenditions], lod)) {
      await storeThumbnailRendition(item, false, () =>
        generateThumbnail(primaryRenditionBitmap, {
          maxDim: lod,
          optimizeForText: item.type === 'text',
        }),
      )
    }
  }

  await prisma.item.update({
    where: { id: item.id },
    data: { scheduledThumbnailProcessing: null },
  })
}
